services:
  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    ports:
      - "8087:8086"   # Host port 8087 -> Container port 8086
    environment:
      - INFLUXDB_HTTP_AUTH_ENABLED=true
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin123
    volumes:
      - ./influxdb:/var/lib/influxdb

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=Grafana@123
    volumes:
      - ./grafana:/var/lib/grafana
    depends_on:
      - influxdb

  jmeter:
    build: .
    container_name: jmeter
    depends_on:
      - influxdb
    volumes:
      - ./tests:/tests
      - ./results/jtl:/results/jtl
      - ./results/logs:/results/logs
      - ./results/reports:/results/reports
    networks:
      - default

networks:
  default:
    name: perfnet